In [1]:
# data 
!wget -nc "https://drive.google.com/uc?export=download&id=1lEccW5Y5_2z00VRtLGOAJOAU6YA9fl6W" -O temp/data/20241225-eComm-Dataset.csv

--2024-12-25 15:13:30--  https://drive.google.com/uc?export=download&id=1lEccW5Y5_2z00VRtLGOAJOAU6YA9fl6W
Resolving drive.google.com (drive.google.com)... 142.250.67.238, 2404:6800:4009:814::200e
Connecting to drive.google.com (drive.google.com)|142.250.67.238|:443... connected.
HTTP request sent, awaiting response... 303 See Other
Location: https://drive.usercontent.google.com/download?id=1lEccW5Y5_2z00VRtLGOAJOAU6YA9fl6W&export=download [following]
--2024-12-25 15:13:30--  https://drive.usercontent.google.com/download?id=1lEccW5Y5_2z00VRtLGOAJOAU6YA9fl6W&export=download
Resolving drive.usercontent.google.com (drive.usercontent.google.com)... 142.250.182.225, 2404:6800:4009:824::2001
Connecting to drive.usercontent.google.com (drive.usercontent.google.com)|142.250.182.225|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 139827 (137K) [application/octet-stream]
Saving to: ‘temp/data/20241225-eComm-Dataset.csv’

temp/data/20241225- 100%[===================>] 136

In [4]:
import pandas as pd
df = pd.read_csv("temp/data/20241225-eComm-Dataset.csv", index_col='ID')
df.head()

n_clicks  n_visits  amount_spent  amount_discount  \
ID                                                        
1476       130        65    213.905831        31.600751   
1535       543        46    639.223004         5.689175   
1807       520       102   1157.402763       844.321606   
1727       702        83   1195.903634       850.041757   
1324       221        84    180.754616        64.283300   

      days_since_registration  profile_information  
ID                                                  
1476                      233                  235  
1535                      228                  170  
1807                      247                  409  
1727                      148                  200  
1324                      243                  259

In [12]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X = scaler.fit_transform(X = df.to_numpy())

In [15]:
X.min(axis=0)

array([-1.92448842, -2.17392389, -1.2378394 , -0.7976828 , -2.02764439,
       -2.0080108 ])

In [41]:
import numpy as np
X_ = np.random.rand(10, 3)

cen_ = X_.min(axis=0) + np.multiply(np.random.rand(2, X_.shape[-1]), X_.max(axis=0))

cen_

array([[0.95639737, 0.19769927, 0.19267741],
       [0.13647397, 0.11108798, 0.69758931]])

array([[0.05314575, 0.35672154, 0.23317544],
       [0.36317373, 0.93174545, 0.84588157],
       [0.99578527, 0.66189959, 0.92056452],
       [0.47989112, 0.19103188, 0.13664252],
       [0.33769922, 0.80318666, 0.17099733],
       [0.18078965, 0.7167105 , 0.97076175],
       [0.85209474, 0.83579817, 0.58367642],
       [0.97067892, 0.39681766, 0.25785335],
       [0.61067082, 0.37526257, 0.82536817],
       [0.76574134, 0.03187148, 0.30292623]])

In [ ]:
# k Means
# 1. assign random centroids
# 2. assign labels
# 3. calculate actual centroids and reassign 

class kMeans:
    def __init__(self, k:int, X: np.ndarray):
        self.k = k 
        self.X = X
        self.assign_random_centroids(self)
        pass

    def assign_random_centroids(self):
        self.centroids = self.X.min(axis=0) + np.multiply(np.random.rand(self.k, self.X.shape[-1]), self.X.max(axis=0))
    
    def assign_labels(self):
        pass
        