In [9]:
import numpy as np
X = np.random.randint(1, 9, size = (10, 3))*10
X

array([[50, 80, 10],
       [60, 80, 70],
       [50, 80, 20],
       [40, 70, 60],
       [20, 20, 70],
       [10, 10, 80],
       [80, 70, 40],
       [70, 80, 40],
       [80, 80, 80],
       [60, 10, 20]])

In [69]:
c = np.random.randint(1, 9, (2, 3))
c = c[:, np.newaxis]
c

array([[[3, 2, 4]],

       [[7, 6, 4]]])

In [49]:
d = (X - c)
d.shape

(2, 10, 3)

In [53]:
yd = np.apply_along_axis(np.linalg.norm, 2, d)
y = np.argmin(yd, 0)
y

array([0, 0, 0, 0, 1, 1, 0, 0, 0, 0])

In [70]:
c1 = np.array([[np.mean(X[y==l], axis=0)] for l in range(2)])
c1

array([[[61.25, 68.75, 42.5 ]],

       [[15.  , 15.  , 75.  ]]])

In [67]:
c

array([[[8, 8, 4]],

       [[6, 2, 7]]])